language: python
sudo: false
deploy:
  provider: pypi
  user: arokem
  password:
    secure: sr2oQY1fOGNQRslNyNLq8B6bVGrvkwIxf23mcYY7F87DPLVvJ799VE1yxKwOJQeVmcFXDwWnxo3pzLvhSYNS3yDHjt9ymJ0+togNx4TUKPPcOHzlTNr+CfTkcx684aypykJjfAgGxUQs5cF2BVutEvKGbCla8OuO+N42Kc8350w=
  on:
    tags: true
    repo: nipy/nitime

python:
- 2.7
- 3.6

env:
- PIP_DEPS="pip pytest pytest-cov coverage coveralls python-coveralls "


python:
- '2.7'
- '3.6'

install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -e .

script:
  - py.test --pyargs nitime --cov-report term-missing --cov=nitime --verbose

after_success:
- coveralls
